# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - run: npm ci
    
    - name: Run tests
      run: npm run test-ci

    - run: mkdir temporario
    - run: cd temporario
    - run: git clone https://github.com/SamuelAraag/Ghibli-Memories.git
    - run: cd Ghibli-Memories
    - run: npm run build-ci
    - run: git config --global user.email "samoelgaaradossantos@gmail.com"
    - run: git config --global user.name "SamuelAraag"
    - run: git add --all
    - run: git commit -m 'deploy'
    - run: git push
    - run: cd ..
    - run: cd ..
    - run: rm -rf temporario
